version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
