version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/o*-collector-contrib/*"
          - "go.opentelemetry.io/contrib/instrumentation/*"
