version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/otel*"
          - "go.opentelemetry.io/otel/sdk"
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/o*-collector-contrib/*"
          - "go.opentelemetry.io/contrib/instrumentation/*"
      frequent:
        patterns:
          - "github.com/aws/aws-sdk-go"
          - "google.golang.org/api"
          - "cloud.google.com/go/*"
      all:
        patterns:
          - "*"
        exclude-patterns:
          - "go.opentelemetry.io/otel*"
          - "go.opentelemetry.io/otel/sdk"
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/o*-collector-contrib/*"
          - "go.opentelemetry.io/contrib/instrumentation/*"
          - "github.com/aws/aws-sdk-go"
          - "google.golang.org/api"
          - "cloud.google.com/go/*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
