run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - unparam
    - unconvert
    - bodyclose
    - decorder
    - makezero
    - nilnil
    - nilerr
    - rowserrcheck
    - tenv
    - wastedassign
    - unparam
    - misspell
    - unconvert
    - depguard

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!**/uuid_test.go"
        deny:
          - pkg: "github.com/gofrs/uuid"
            desc: 'use github.com/google/uuid instead'
          - pkg: "golang.org/x/exp/slices"
            desc: 'use "slices" instead'