run:
  timeout: 5m
  go: '1.20'

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - decorder
    - makezero
    - nilnil
    - nilerr
    - rowserrcheck
    - tenv
    - wastedassign
    - unparam
    - misspell
    - unconvert
    - depguard

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

linters-settings:
  depguard:
    # Kind of list is passed in.
    # Allowed values: allowlist|denylist
    # Default: denylist
    list-type: denylist
    # Check the list against standard lib.
    # Default: false
    include-go-root: true