// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-go-kit/filemanager (interfaces: FileManager)
//
// Generated by this command:
//
//	mockgen -destination=mock_filemanager/mock_filemanager.go -package mock_filemanager github.com/rudderlabs/rudder-go-kit/filemanager FileManager
//

// Package mock_filemanager is a generated GoMock package.
package mock_filemanager

import (
	context "context"
	io "io"
	os "os"
	reflect "reflect"
	time "time"

	filemanager "github.com/rudderlabs/rudder-go-kit/filemanager"
	gomock "go.uber.org/mock/gomock"
)

// MockFileManager is a mock of FileManager interface.
type MockFileManager struct {
	ctrl     *gomock.Controller
	recorder *MockFileManagerMockRecorder
	isgomock struct{}
}

// MockFileManagerMockRecorder is the mock recorder for MockFileManager.
type MockFileManagerMockRecorder struct {
	mock *MockFileManager
}

// NewMockFileManager creates a new mock instance.
func NewMockFileManager(ctrl *gomock.Controller) *MockFileManager {
	mock := &MockFileManager{ctrl: ctrl}
	mock.recorder = &MockFileManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileManager) EXPECT() *MockFileManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileManager) Delete(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileManagerMockRecorder) Delete(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileManager)(nil).Delete), ctx, keys)
}

// Download mocks base method.
func (m *MockFileManager) Download(arg0 context.Context, arg1 io.WriterAt, arg2 string, arg3 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockFileManagerMockRecorder) Download(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFileManager)(nil).Download), arg0, arg1, arg2, arg3)
}

// GetDownloadKeyFromFileLocation mocks base method.
func (m *MockFileManager) GetDownloadKeyFromFileLocation(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadKeyFromFileLocation", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDownloadKeyFromFileLocation indicates an expected call of GetDownloadKeyFromFileLocation.
func (mr *MockFileManagerMockRecorder) GetDownloadKeyFromFileLocation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadKeyFromFileLocation", reflect.TypeOf((*MockFileManager)(nil).GetDownloadKeyFromFileLocation), arg0)
}

// GetObjectNameFromLocation mocks base method.
func (m *MockFileManager) GetObjectNameFromLocation(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectNameFromLocation", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectNameFromLocation indicates an expected call of GetObjectNameFromLocation.
func (mr *MockFileManagerMockRecorder) GetObjectNameFromLocation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectNameFromLocation", reflect.TypeOf((*MockFileManager)(nil).GetObjectNameFromLocation), arg0)
}

// ListFilesWithPrefix mocks base method.
func (m *MockFileManager) ListFilesWithPrefix(ctx context.Context, startAfter, prefix string, maxItems int64) filemanager.ListSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesWithPrefix", ctx, startAfter, prefix, maxItems)
	ret0, _ := ret[0].(filemanager.ListSession)
	return ret0
}

// ListFilesWithPrefix indicates an expected call of ListFilesWithPrefix.
func (mr *MockFileManagerMockRecorder) ListFilesWithPrefix(ctx, startAfter, prefix, maxItems any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesWithPrefix", reflect.TypeOf((*MockFileManager)(nil).ListFilesWithPrefix), ctx, startAfter, prefix, maxItems)
}

// Prefix mocks base method.
func (m *MockFileManager) Prefix() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prefix")
	ret0, _ := ret[0].(string)
	return ret0
}

// Prefix indicates an expected call of Prefix.
func (mr *MockFileManagerMockRecorder) Prefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prefix", reflect.TypeOf((*MockFileManager)(nil).Prefix))
}

// SetTimeout mocks base method.
func (m *MockFileManager) SetTimeout(timeout time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTimeout", timeout)
}

// SetTimeout indicates an expected call of SetTimeout.
func (mr *MockFileManagerMockRecorder) SetTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeout", reflect.TypeOf((*MockFileManager)(nil).SetTimeout), timeout)
}

// Upload mocks base method.
func (m *MockFileManager) Upload(arg0 context.Context, arg1 *os.File, arg2 ...string) (filemanager.UploadedFile, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upload", varargs...)
	ret0, _ := ret[0].(filemanager.UploadedFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileManagerMockRecorder) Upload(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileManager)(nil).Upload), varargs...)
}

// UploadReader mocks base method.
func (m *MockFileManager) UploadReader(ctx context.Context, objName string, rdr io.Reader) (filemanager.UploadedFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadReader", ctx, objName, rdr)
	ret0, _ := ret[0].(filemanager.UploadedFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadReader indicates an expected call of UploadReader.
func (mr *MockFileManagerMockRecorder) UploadReader(ctx, objName, rdr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadReader", reflect.TypeOf((*MockFileManager)(nil).UploadReader), ctx, objName, rdr)
}
