// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-go-kit/stats (interfaces: Stats,Measurement)
//
// Generated by this command:
//
//	mockgen -destination=mock_stats/mock_stats.go -package mock_stats github.com/rudderlabs/rudder-go-kit/stats Stats,Measurement
//

// Package mock_stats is a generated GoMock package.
package mock_stats

import (
	context "context"
	reflect "reflect"
	time "time"

	stats "github.com/rudderlabs/rudder-go-kit/stats"
	gomock "go.uber.org/mock/gomock"
)

// MockStats is a mock of Stats interface.
type MockStats struct {
	ctrl     *gomock.Controller
	recorder *MockStatsMockRecorder
	isgomock struct{}
}

// MockStatsMockRecorder is the mock recorder for MockStats.
type MockStatsMockRecorder struct {
	mock *MockStats
}

// NewMockStats creates a new mock instance.
func NewMockStats(ctrl *gomock.Controller) *MockStats {
	mock := &MockStats{ctrl: ctrl}
	mock.recorder = &MockStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStats) EXPECT() *MockStatsMockRecorder {
	return m.recorder
}

// NewSampledTaggedStat mocks base method.
func (m *MockStats) NewSampledTaggedStat(name, statType string, tags stats.Tags) stats.Measurement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSampledTaggedStat", name, statType, tags)
	ret0, _ := ret[0].(stats.Measurement)
	return ret0
}

// NewSampledTaggedStat indicates an expected call of NewSampledTaggedStat.
func (mr *MockStatsMockRecorder) NewSampledTaggedStat(name, statType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSampledTaggedStat", reflect.TypeOf((*MockStats)(nil).NewSampledTaggedStat), name, statType, tags)
}

// NewStat mocks base method.
func (m *MockStats) NewStat(name, statType string) stats.Measurement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewStat", name, statType)
	ret0, _ := ret[0].(stats.Measurement)
	return ret0
}

// NewStat indicates an expected call of NewStat.
func (mr *MockStatsMockRecorder) NewStat(name, statType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStat", reflect.TypeOf((*MockStats)(nil).NewStat), name, statType)
}

// NewTaggedStat mocks base method.
func (m *MockStats) NewTaggedStat(name, statType string, tags stats.Tags) stats.Measurement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTaggedStat", name, statType, tags)
	ret0, _ := ret[0].(stats.Measurement)
	return ret0
}

// NewTaggedStat indicates an expected call of NewTaggedStat.
func (mr *MockStatsMockRecorder) NewTaggedStat(name, statType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTaggedStat", reflect.TypeOf((*MockStats)(nil).NewTaggedStat), name, statType, tags)
}

// NewTracer mocks base method.
func (m *MockStats) NewTracer(name string) stats.Tracer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTracer", name)
	ret0, _ := ret[0].(stats.Tracer)
	return ret0
}

// NewTracer indicates an expected call of NewTracer.
func (mr *MockStatsMockRecorder) NewTracer(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTracer", reflect.TypeOf((*MockStats)(nil).NewTracer), name)
}

// RegisterCollector mocks base method.
func (m *MockStats) RegisterCollector(c stats.Collector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCollector", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterCollector indicates an expected call of RegisterCollector.
func (mr *MockStatsMockRecorder) RegisterCollector(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCollector", reflect.TypeOf((*MockStats)(nil).RegisterCollector), c)
}

// Start mocks base method.
func (m *MockStats) Start(ctx context.Context, goFactory stats.GoRoutineFactory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, goFactory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockStatsMockRecorder) Start(ctx, goFactory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStats)(nil).Start), ctx, goFactory)
}

// Stop mocks base method.
func (m *MockStats) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockStatsMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStats)(nil).Stop))
}

// MockMeasurement is a mock of Measurement interface.
type MockMeasurement struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementMockRecorder
	isgomock struct{}
}

// MockMeasurementMockRecorder is the mock recorder for MockMeasurement.
type MockMeasurementMockRecorder struct {
	mock *MockMeasurement
}

// NewMockMeasurement creates a new mock instance.
func NewMockMeasurement(ctrl *gomock.Controller) *MockMeasurement {
	mock := &MockMeasurement{ctrl: ctrl}
	mock.recorder = &MockMeasurementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurement) EXPECT() *MockMeasurementMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockMeasurement) Count(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Count", n)
}

// Count indicates an expected call of Count.
func (mr *MockMeasurementMockRecorder) Count(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockMeasurement)(nil).Count), n)
}

// Gauge mocks base method.
func (m *MockMeasurement) Gauge(value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Gauge", value)
}

// Gauge indicates an expected call of Gauge.
func (mr *MockMeasurementMockRecorder) Gauge(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockMeasurement)(nil).Gauge), value)
}

// Increment mocks base method.
func (m *MockMeasurement) Increment() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Increment")
}

// Increment indicates an expected call of Increment.
func (mr *MockMeasurementMockRecorder) Increment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockMeasurement)(nil).Increment))
}

// Observe mocks base method.
func (m *MockMeasurement) Observe(value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Observe", value)
}

// Observe indicates an expected call of Observe.
func (mr *MockMeasurementMockRecorder) Observe(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockMeasurement)(nil).Observe), value)
}

// RecordDuration mocks base method.
func (m *MockMeasurement) RecordDuration() func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordDuration")
	ret0, _ := ret[0].(func())
	return ret0
}

// RecordDuration indicates an expected call of RecordDuration.
func (mr *MockMeasurementMockRecorder) RecordDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDuration", reflect.TypeOf((*MockMeasurement)(nil).RecordDuration))
}

// SendTiming mocks base method.
func (m *MockMeasurement) SendTiming(duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendTiming", duration)
}

// SendTiming indicates an expected call of SendTiming.
func (mr *MockMeasurementMockRecorder) SendTiming(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTiming", reflect.TypeOf((*MockMeasurement)(nil).SendTiming), duration)
}

// Since mocks base method.
func (m *MockMeasurement) Since(start time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Since", start)
}

// Since indicates an expected call of Since.
func (mr *MockMeasurementMockRecorder) Since(start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockMeasurement)(nil).Since), start)
}
